music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:new, :index]
end

music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  title      :string           not null
#  year       :integer          not null
#  live       :integer          not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :name, :title, :band_id, :year, :live, presence: true

  belongs_to :band,
  foreign_key: :band_id

  has_many :tracks,
  foreign_key: :album_id,
  dependant: :destroy

end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
  foreign_key: :band_id,
  dependant: :destroy

  has_many :tracks,
  through: :albums,
  source: :tracks
end

music_app/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id       :integer          not null, primary key
#  title    :string           not null
#  ord      :integer          not null
#  lyrics   :text
#  regular  :integer          not null
#  album_id :integer
#

class Track < ApplicationRecord
  validates :title, :ord, :regular, :album_id, presence: true

  belongs_to :album,
  foreign_key: :album_id

  has_one :band,
  through: :album,
  source: :band
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :session_token, presence: true
  validates :password, presence: true, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show

  end

  def new

  end

  def create

  end

  def destroy

  end

  def edit
    
  end

  def update

  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user
    redirect_to new_session_url unless logged_in?
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = current_band
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:sucess] = "Successfully Added #{@band.name}"
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @band = current_band
    @band.destroy!
  end

  def edit
    @band = current_band
    render :edit
  end

  def update
    @band = current_band
    if @band.update_attributes
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
  end

  private

  def bands_params
    params.require(:bands).permit(:name)
  end

  def current_band
    Band.find(params[:id])
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login_user!(user)
      redirect_to bands_url
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

music_app/app/controllers/tracks_controller.rb
class AlbumsController < ApplicationController
  def show
    @album =
  end

  def new

  end

  def create

  end

  def destroy

  end

  def edit

  end

  def update

  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      flash[:sucess] = 'Successfully Logged In'
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_helper
    "<input
  type='hidden'
  name='authenticity_token'
  value='<%= form_authenticity_token %>'
/>".html_safe
  end
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class='cf'>Music App</h1>
        <nav>
        <p class='cf'><%= current_user.email if current_user%></p>
        <% if logged_in? %>
          <p>
          <form action="session_url" method="post">
            <%= auth_helper %>
            <input type="hidden" name="_method" value="delete">
            <input type="submit" name="" value="Log Out!">
          </form>
        </p>
        <% else %>
          <p>
          <a href="<%= session_url%>" method='post'>Sign In!</a>
          </p>
          <p>
          <a href="<%= new_user_url%>" method='post'>Sign Up!</a>
        </p>
        <% end %>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

music_app/app/views/session/new.html.erb
<h2>Log In!</h2><br>
<form action="<%=session_url%>" method="post">
  <%= auth_helper %>

  <label for="user[email]">Email:</label>
  <input type="text" name="user[email]" value=""><br>

  <label for="user[password]">Password:</label>
  <input type="password" name="user[password]" value=""><br>


  <input type="submit" name="" value="Log In!">
</form>

music_app/app/views/users/new.html.erb
<h2>Create a User!</h2><br>
<form action="<%=users_url%>" method="post">
  <%= auth_helper %>

  <label for="user[email]">Email:</label>
  <input type="text" name="user[email]" value=""><br>

  <label for="user[password]">Password:</label>
  <input type="password" name="user[password]" value=""><br>


  <input type="submit" name="" value="Join!">
</form>